version: '3'

services:
  mongodb:
    image: mongo:5.0
    ports:
      - '10002:27017'
    volumes:
      - ~/docker-volumes/personal/cqrs-mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo

